import os
import numpy as np
import pandas as pd

from hedging_env import HedgingEnv


def main():
    ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    csv_path = os.path.join(ROOT, "data", "historical_hedging_data.csv")
    out_path = os.path.join(ROOT, "output", "step_data_example.csv")

    if not os.path.exists(csv_path):
        print(f"CSV not found: {csv_path}\nRun `python src/generate_contract.py` to create it.")
        return

    # Load CSV (expect columns generated by generate_contract.py)
    df = pd.read_csv(csv_path, parse_dates=["timestamp"]) 

    # Map columns to env inputs
    option_prices = df["option_price"].values
    stock_prices = df["underlying_price"].values
    moneyness = df["moneyness"].values
    ttm = df["time_to_maturity"].values
    timestamps = df["timestamp"].values

    # Create environment
    env = HedgingEnv(
        option_prices=option_prices,
        stock_prices=stock_prices,
        moneyness=moneyness,
        ttm=ttm,
        timestamps=timestamps,
        normalize=False,
        verbose=True
    )

    # Reset and run a few random steps
    obs = env.reset()
    print("Initial observation:", obs)

    n_steps = 5
    for i in range(n_steps):
        action = env.action_space.sample()
        next_state, reward, done, info = env.step(action)
        print(f"Step {i+1}: action={action[0]:.4f}, reward={reward:.6f}, done={done}")
        if done:
            break

    # Export step data
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    success = env.export_step_data(out_path)
    if success:
        print(f"Step data exported to: {out_path}")
    else:
        print("No step data to export.")


if __name__ == '__main__':
    main()
